### ISSUE TITLE
SquirrelPAK 1201 Beta 1 Tracking

### ISSUE THREAD

**Issue by SquirrelCraft** [SquirrelCraft/SquirrelPAKs#6]
Issue to track TODO and issues until Beta 1 - Once 

- [x] Setup squirrelpak scripts 
- [x] Redo Menu
- [x] Select Music
- [ ] Select Pano
- [ ] Create starter kits
- [ ] Check all user config
   - [ ] Set Key Binds
   - [ ] Set Default Options
- [ ] Check server config
